# DRACUTUX
gui:
  theme:
    activeBorderColor:
      - "#ff77cc"
      - bold
    inactiveBorderColor:
      - "#bb99ff"

    searchingActiveBorderColor:
      - "#88eeff"
      - bold

    optionsTextColor:
      - "#6677aa"

    selectedLineBgColor:
      - "#444455"

    inactiveViewSelectedLineBgColor:
      - bold

    cherryPickedCommitFgColor:
      - "#6677aa"

    cherryPickedCommitBgColor:
      - "#88eeff"

    markedBaseCommitFgColor:
      - "#88eeff"

    markedBaseCommitBgColor:
      - "#eeff88"

    unstagedChangesColor:
      - "#ff5555"

    defaultFgColor:
      - "#ffffee"
