[language-server.emmet-lsp]
command = "emmet-language-server"
args = ["--stdio"]

[[language]]
name = "toml"
roots = ["."]

[[language]]
name = "ghostty"
file-types = [{ glob = "ghostty/config" }, { glob = "ghostty/themes/*" }]

[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "emmet-lsp"]

[[language]]
name = "javascript"
language-servers = ["typescript-language-server", "emmet-lsp"]
