inherits = "dracutux"

[palette]
base = "#222233"
base2 = "#333344"
base3 = "#555566"
selection = "#554488"
text = "#eeeeee"
text2 = "#ffffee"
grey = "#aaaabb"
comment = "#7755aa"
cyan = "#aaddee"
cyan2 = "#bbeeee"
green = "#88dd88"
teal = "#99ddbb"
pink = "#dd88bb"
pink2 = "#ee99dd"
purple = "#bb99ee"
blue = "#88bbee"
red = "#dd7777"
orange = "#eeaa88"
yellow = "#eedd99"
yellow2 = "#eeeeaa"
