# Syntax highlighting
# -------------------
attribute = { fg = "teal", modifiers = ["italic"] }

type = "cyan"
"type.builtin" = { fg = "cyan", modifiers = ["italic"] }
"type.enum.variant" = { fg = "blue" }

"constructor" = "cyan"

"constant" = "purple"
"constant.character" = "orange"
"constant.character.escape" = "pink"

"string" = "yellow"
"string.regexp" = "red"
"string.special" = "blue"
"string.special.symbol" = "orange"

"comment" = { fg = "comment", modifiers = ["italic"] }

"variable" = "text"
"variable.parameter" = { fg = "orange", modifiers = ["italic"] }
"variable.builtin" = "purple"
"variable.other.member" = { fg = "teal" }

"label" = "cyan" # used for lifetimes

"punctuation.special" = "blue"

"keyword" = { fg = "pink", modifiers = ["italic"] }

"operator" = "pink"

"function" = "green"
"function.macro" = "purple"

"tag" = "pink"

"namespace" = { fg = "purple" }

"special" = "blue" # fuzzy highlight

"markup.heading.1" = { fg = "purple", modifiers = ["bold"] }
"markup.heading.2" = { fg = "pink", modifiers = ["bold"] }
"markup.heading.3" = { fg = "orange", modifiers = ["bold"] }
"markup.heading.4" = { fg = "yellow", modifiers = ["bold"] }
"markup.heading.5" = { fg = "green", modifiers = ["bold"] }
"markup.heading.6" = { fg = "cyan", modifiers = ["bold"] }
"markup.list" = "teal"
"markup.list.unchecked" = "cyan"
"markup.list.checked" = "green"
"markup.bold" = { fg = "orange", modifiers = ["bold"] }
"markup.italic" = { fg = "yellow", modifiers = ["italic"] }
"markup.link.url" = { fg = "blue", modifiers = ["italic", "underlined"] }
"markup.link.text" = "pink"
"markup.link.label" = "red"
"markup.raw" = "yellow"
"markup.quote" = { fg = "yellow", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }

"diff.plus" = "green"
"diff.minus" = "red"
"diff.delta" = "yellow"

# User Interface
# --------------
"ui.background" = { fg = "text", bg = "base" }

"ui.linenr" = { fg = "comment", modifiers = ["dim"] }
"ui.linenr.selected" = { fg = "text" }

"ui.statusline" = { fg = "text", bg = "ui_base" }
"ui.statusline.inactive" = { fg = "subtle_text", bg = "ui_base" }
"ui.statusline.normal" = { fg = "base", bg = "purple", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "base", bg = "green", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "base", bg = "cyan", modifiers = ["bold"] }

"ui.popup" = { fg = "text", bg = "ui_base" }
"ui.popup.info" = { fg = "purple", bg="base" }
"ui.window" = { fg = "ui_base" }
"ui.help" = { fg = "subtle_text", bg = "ui_base" }

"ui.bufferline" = { fg = "subtle_text", bg = "ui_base" }
"ui.bufferline.active" = { fg = "text", bg = "base", modifiers = [
  "bold",
  "italic",
] }
"ui.bufferline.background" = { bg = "ui_base" }

"ui.text" = "text"
"ui.text.focus" = { fg = "text", bg = "ui_selection", modifiers = ["bold"] }
"ui.text.inactive" = { fg = "comment" }
"ui.text.directory" = { fg = "purple" }

"ui.virtual" = "selection"
"ui.virtual.ruler" = { bg = "ui_base" }
"ui.virtual.indent-guide" = "ui_selection"
"ui.virtual.inlay-hint" = { fg = "comment", bg = "ui_base" }
"ui.virtual.jump-label" = { fg = "red", modifiers = ["bold"] }

"ui.selection" = { bg = "selection" }

"ui.cursor" = { fg = "base", bg = "subtle_text" }
"ui.cursor.match" = { fg = "orange", modifiers = ["bold"] }

"ui.cursor.primary.normal" = { fg = "base", bg = "purple" }
"ui.cursor.primary.insert" = { fg = "base", bg = "green" }
"ui.cursor.primary.select" = { fg = "base", bg = "cyan" }

"ui.cursorline.primary" = { bg = "ui_base" }

"ui.highlight" = { fg = "text", bg = "ui_base", modifiers = ["bold"] }

"ui.menu" = { fg = "text", bg = "ui_base" }
"ui.menu.selected" = { fg = "text", bg = "ui_selection", modifiers = ["bold"] }

"diagnostic.error" = { underline = { color = "red", style = "curl" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.info" = { underline = { color = "cyan", style = "curl" } }
"diagnostic.hint" = { underline = { color = "teal", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }

error = "red"
warning = "yellow"
info = "cyan"
hint = "teal"

[palette]
base = "#222233"
ui_base = "#111122"

text = "#ffffee"
subtle_text = "#bbbbcc"

selection = "#443377"
ui_selection = "#444455"

comment = "#6677aa"

cyan = "#88eeff"
blue = "#55bbff"

green = "#55ff77"
teal = "#66eebb"

pink = "#ff77cc"

purple = "#bb99ff"

red = "#ff5555"

yellow = "#eeff88"
orange = "#ffbb77"
