inherits = "dracutux"

[palette]
base = "#eeeeff"
ui_base = "#ffffff"

text = "#555544"
subtle_text = "#9999aa"

selection = "#ddccff"
ui_selection = "#ccccdd"

comment = "#aabbee"

cyan = "#5599aa"
blue = "#5588bb"

green = "#339955"
teal = "#449988"

pink = "#cc66aa"

purple = "#7744bb"

red = "#ee6666"

orange = "#cc7755"

yellow = "#aa9944"
