#!/bin/sh

# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# Note: the "Super" modifier is also known as Logo, GUI, Windows, Mod4, etc.

mod="Mod4"

### Applications
riverctl map normal $mod+Shift Return spawn ghostty
riverctl map normal $mod P spawn fuzzel

### Section
riverctl map normal $mod Q close
riverctl map normal $mod+Shift E spawn mypower.sh

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal $mod J focus-view next
riverctl map normal $mod K focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal $mod+Shift J swap next
riverctl map normal $mod+Shift K swap previous

# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal $mod Period focus-output next
riverctl map normal $mod Comma focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# Super+Return to bump the focused view to the top of the layout stack
riverctl map normal $mod Return zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal $mod H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal $mod L send-layout-cmd rivertile "main-ratio +0.05"
# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal $mod+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal $mod+Shift L send-layout-cmd rivertile "main-count -1"

# Super + Left Mouse Button to move views
riverctl map-pointer normal $mod BTN_LEFT move-view
# Super + Right Mouse Button to resize views
riverctl map-pointer normal $mod BTN_RIGHT resize-view
# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal $mod BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
  tags=$((1 << ($i - 1)))
  # Super+[1-9] to focus tag [0-8]
  riverctl map normal $mod $i set-focused-tags $tags
  # Super+Shift+[1-9] to tag focused view with tag [0-8]
  riverctl map normal $mod+Shift $i set-view-tags $tags
  # Super+Control+[1-9] to toggle focus of tag [0-8]
  riverctl map normal $mod+Control $i toggle-focused-tags $tags
  # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
  riverctl map normal $mod+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal $mod 0 set-focused-tags $all_tags
riverctl map normal $mod+Shift 0 set-view-tags $all_tags

# Super+Space to toggle float
riverctl map normal $mod Space toggle-float
# Super+F to toggle fullscreen
riverctl map normal $mod F toggle-fullscreen

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough
# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough
# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
  # Eject the optical drive (well if you still have one that is)
  riverctl map $mode None XF86Eject spawn 'eject -T'

  # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
  riverctl map $mode None XF86AudioRaiseVolume  spawn 'mycontrol.sh volume up 10'
  riverctl map $mode None XF86AudioLowerVolume  spawn 'mycontrol.sh volume down 10'
  riverctl map $mode None XF86AudioMute         spawn 'mycontrol.sh volume mute'
  riverctl map -repeat $mode Control Up         spawn 'mycontrol.sh volume up 10'
  riverctl map -repeat $mode Control Down       spawn 'mycontrol.sh volume down 10'

  # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
  riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
  riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
  riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
  riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

  # Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
  riverctl map $mode None XF86MonBrightnessUp   spawn 'mycontrol.sh brightnessctl up 10'
  riverctl map $mode None XF86MonBrightnessDown spawn 'mycontrol.sh brightnessctl down 10'
done

# Print
riverctl map normal None Print spawn 'myshot.sh'
riverctl map normal $mod Print spawn 'myshot.sh full'

# Set background and border color
riverctl background-color 0x21222c
riverctl border-color-focused 0xbd93f9
riverctl border-color-unfocused 0x6272a4

# Set keyboard repeat rate
riverctl set-repeat 50 300

riverctl xcursor-theme Adwaita

riverctl rule-add ssd
riverctl rule-add -app-id float float

# Make all views with an app-id that starts with "float" and title "foo" start floating.
# riverctl rule-add -app-id 'float*' -title 'foo' float
# Make all views with app-id "bar" and any title use client-side decorations
# riverctl rule-add -app-id "bar" csd

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile


systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river
systemctl --user restart xdg-desktop-portal

rivertile -view-padding 4 -outer-padding 4 &
gammastep -O3500 &
mako &
waybar &
swayidle -w \
  timeout 600 "waylock.sh" \
  timeout 601 "wlopm --off '*'" resume "wlopm --on '*'" \
  timeout 1200 "systemctl suspend" \
  before-sleep "waylock.sh" &
# ghostty &
kanshi &
