theme = "dracula"

[editor]
true-color = true
auto-format = false
color-modes = true

[editor.statusline]
right = ["diagnostics", "selections", "position", "position-percentage", "file-encoding", "file-line-ending", "file-type"]

[editor.lsp]
display-messages = true
