# Colors (Dracutux)

# Default colors
[colors.primary]
background = '#222233'
foreground = '#ffffee'

# Normal colors
[colors.normal]
black   = '#111122'
red     = '#ff5555'
green   = '#55ff77'
yellow  = '#eeff88'
blue    = '#bb99ff'
magenta = '#ff77cc'
cyan    = '#88eeff'
white   = '#ffffee'

# Bright colors
[colors.bright]
black   = '#444455'
red     = '#ff5555'
green   = '#66eebb'
yellow  = '#ffbb77'
blue    = '#bb99ff'
magenta = '#ff77cc'
cyan    = '#66bbff'
white   = '#ffffee'
